"""baseline phase 1 tables

Revision ID: 7208c771909c
Revises:
Create Date: 2026-09-22 12:36:47.731152

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7208c771909c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "author",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("family_name", sa.String(), nullable=True),
        sa.Column("given_name", sa.String(), nullable=True),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("orcid", sa.String(), nullable=True),
        sa.Column("other_ids", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("author", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_author_orcid"), ["orcid"], unique=True)

    op.create_table(
        "record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("abstract", sa.String(), nullable=True),
        sa.Column("publication_year", sa.Integer(), nullable=True),
        sa.Column("publication_month", sa.Integer(), nullable=True),
        sa.Column("publication_day", sa.Integer(), nullable=True),
        sa.Column("journal", sa.String(), nullable=True),
        sa.Column("conference_name", sa.String(), nullable=True),
        sa.Column("volume", sa.String(), nullable=True),
        sa.Column("issue", sa.String(), nullable=True),
        sa.Column("pages", sa.String(), nullable=True),
        sa.Column("doi", sa.String(), nullable=True),
        sa.Column("pmid", sa.String(), nullable=True),
        sa.Column("issn", sa.String(), nullable=True),
        sa.Column("isbn", sa.String(), nullable=True),
        sa.Column("other_ids", sa.JSON(), nullable=False),
        sa.Column("publication_type", sa.String(), nullable=True),
        sa.Column("keywords", sa.JSON(), nullable=False),
        sa.Column("language", sa.String(), nullable=True),
        sa.Column("publisher", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("record", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_record_doi"), ["doi"], unique=False)
        batch_op.create_index(batch_op.f("ix_record_pmid"), ["pmid"], unique=False)

    op.create_table(
        "source_file",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("path", sa.String(), nullable=True),
        sa.Column("format", sa.String(), nullable=False),
        sa.Column("imported_at", sa.DateTime(), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "activity_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("action_type", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["record.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("activity_log", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_activity_log_record_id"), ["record_id"], unique=False
        )

    op.create_table(
        "record_author",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("author_order", sa.Integer(), nullable=False),
        sa.Column("affiliations", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["author.id"],
        ),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["record.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("record_author", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_record_author_author_id"), ["author_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_record_author_record_id"), ["record_id"], unique=False
        )

    op.create_table(
        "record_source",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=False),
        sa.Column("source_file_id", sa.Integer(), nullable=False),
        sa.Column("raw_fields", sa.JSON(), nullable=False),
        sa.Column("imported_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["record.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_file_id"],
            ["source_file.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("record_source", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_record_source_record_id"), ["record_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_record_source_source_file_id"),
            ["source_file_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("record_source", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_record_source_source_file_id"))
        batch_op.drop_index(batch_op.f("ix_record_source_record_id"))

    op.drop_table("record_source")
    with op.batch_alter_table("record_author", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_record_author_record_id"))
        batch_op.drop_index(batch_op.f("ix_record_author_author_id"))

    op.drop_table("record_author")
    with op.batch_alter_table("activity_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_activity_log_record_id"))

    op.drop_table("activity_log")
    op.drop_table("source_file")
    with op.batch_alter_table("record", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_record_pmid"))
        batch_op.drop_index(batch_op.f("ix_record_doi"))

    op.drop_table("record")
    with op.batch_alter_table("author", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_author_orcid"))

    op.drop_table("author")
    # ### end Alembic commands ###
